### ISSUE TITLE
If you cannot login, please report it here. | 如果你无法登陆，请在这里反映

### ISSUE THREAD

**Issue by GamerNoTitle** [GamerNoTitle/Valorant-Shop-Query#124]
### 请选择你所使用的Valora版本

正式版 https://val.bili33.top

### 请输入你遇到问题的网址（例如：https://val.bili33.top/market）

https://val.bili33.top/api/login

### 请提供复现的步骤

直接登录，然后报错

### 请贴入报错页面弹出的日志

```shell
服务器发生了以下错误：
Traceback (most recent call last):
File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 971, in json
return complexjson.loads(self.text, **kwargs)
File "/usr/local/lib/python3.10/site-packages/simplejson/__init__.py", line 514, in loads
return _default_decoder.decode(s)
File "/usr/local/lib/python3.10/site-packages/simplejson/decoder.py", line 386, in decode
obj, end = self.raw_decode(s)
File "/usr/local/lib/python3.10/site-packages/simplejson/decoder.py", line 416, in raw_decode
return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 2529, in wsgi_app
response = self.full_dispatch_request()
File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1825, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1823, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1799, in dispatch_request
return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
File "/app/app.py", line 233, in RiotLogin_handler
return RiotLogin(app, request)
File "/app/utils/api.py", line 41, in RiotLogin
user.auth()
File "/app/utils/RiotLogin.py", line 56, in auth
tokens = self.authorize(MFACode)
File "/app/utils/RiotLogin.py", line 94, in authorize
data = r.json()
File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 975, in json
raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by GamerNoTitle** [comment]
2023.8.30 又可以登陆了 暂时不改
本issue仍然保持开放状态，如果无法登陆请在此反映

**Comment by GamerNoTitle** [comment]
注：关于RiotClient的UA，以`riotClientBuild`为`70.0.0.247.1382`为例，UA应该呈现为`RiotClient/70.0.0.247.1382 riot-status (Windows;10;;Professional, x64)`

**Comment by GamerNoTitle** [comment]
已经对UA进行了修改，如果后期出现无法登陆的情况请在此反映

**Comment by kevinyasuo** [comment]
![image](https://github.com/GamerNoTitle/Valora/assets/101216256/9325e933-fa1b-473c-99dd-f9e3982f6daa)

**Comment by kevinyasuo** [comment]
登录不了

**Comment by GamerNoTitle** [comment]
> 登录不了
> 

你用的是啥浏览器呢？看起来是在设置cookie的时候出现了问题，登录的时候获取不到你的玩家名，是新号吗？

**Comment by kevinyasuo** [comment]
哦~(⊙o⊙)是的！是新号，原来是这个问题啊~，还以为是登录太多账号造成的呢

**Comment by GamerNoTitle** [comment]
> 哦~(⊙o⊙)是的！是新号，原来是这个问题啊~，还以为是登录太多账号造成的呢

新号必须设定了玩家名+tag过后才可以登录，例如Valora#val

**Comment by vitorhenrique123** [comment]
Hey hey!

I'm encountering the same issue after setting up on a VPS. It seems like Cloudflare might be blocking it? I'm receiving a 403 error on the request.

**Comment by GamerNoTitle** [comment]
> Hey hey!
> 
> I'm encountering the same issue after setting up on a VPS. It seems like Cloudflare might be blocking it? I'm receiving a 403 error on the request.

Hi, thank you for your report.
Have you ever tried to login with this wheel? https://github.com/Prodzify/Riot-auth
If you haven't, try to use it and see the result is still 403 or not.

**Comment by vitorhenrique123** [comment]
Hey Hey!

Thanks for the answer!

I tested with this lib and received the following message:
![image](https://github.com/GamerNoTitle/Valora/assets/18515574/41893b5b-380b-44ce-a57a-2f4afae7cea4)

**Comment by GamerNoTitle** [comment]
> Hey Hey!
> 
> Thanks for the answer!
> 
> I tested with this lib and received the following message: ![image](https://private-user-images.githubusercontent.com/18515574/338070383-41893b5b-380b-44ce-a57a-2f4afae7cea4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwMDA4NTIsIm5iZiI6MTcxODAwMDU1MiwicGF0aCI6Ii8xODUxNTU3NC8zMzgwNzAzODMtNDE4OTNiNWItMzgwYi00NGNlLWE1N2EtMmY0YWZhZTdjZWE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEwVDA2MjIzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM2MDkzNTM0N2I4N2NkOGZlNDUyZDgzNTk2Y2VmYjAzNTliNWNjOTRhYzFhMzcwYjlmNDFjMDAyZDczYzYxNzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.c9cIQmpMXsNNiGZCQmiviZKEcvDe_uUVeEhvDYym_ms)

It seems that you are not using https://github.com/ohlunaaa/Riot-auth but https://github.com/ohlunaaa/Valorant-auth
Besides, I've tested https://github.com/ohlunaaa/Riot-auth by myself and it seemed that the way to bypass cloudflare's WAF is now unable to use. Unless the lib was updated or I made a lib to bypass this, or we can't log account in this way :<

**Comment by GamerNoTitle** [comment]
I will try to make one later. If I have further progress, I will post it here. Thank you for your report or I will not know this :D

**Comment by vitorhenrique123** [comment]
Sorry about that! I sent you the wrong screenshot. I tested both libraries. The first one (your link) actually returned a 403 error too. I'm going to try some methods to bypass Cloudflare as well. I'll send updates here as soon as I can.

**Comment by GamerNoTitle** [comment]
> Sorry about that! I sent you the wrong screenshot. I tested both libraries. The first one (your link) actually returned a 403 error too. I'm going to try some methods to bypass Cloudflare as well. I'll send updates here as soon as I can.

I've tried using VPN to do the http request and it would work. If you cannot login, you can try using VPN.
It seems that Riot Games has blocked some ASN to access their log service.

**Comment by wiop93256** [comment]
500 服务器发生了以下错误：
Server is currently under high load, we are unable to finish your requests at this time. Please try again later.
Traceback (most recent call last):
File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1823, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1799, in dispatch_request
return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
File "/app/app.py", line 170, in market_handler
return market(app, request, g.lang)
File "/app/utils/Register.py", line 59, in market
weapon_target = weapon(weapon_item['OfferID'], weapon_item["Cost"]["85ad13f7-3d1b-5128-9eb2-7cd8ee0b5741"], lang=str(lang))
File "/app/utils/Weapon.py", line 36, in __init__
c.execute(
sqlite3.OperationalError: database is locked

你可以尝试【刷新网页】或者点击下方的“重置网站数据”按钮来解决这个问题。
如果你已经点击了下面的按钮，但仍然出现了这个问题，请尝试清除浏览器的cookie来重置会话
如果上面这两种方法你都已经尝试过了，那么请带着此错误信息联系开发者！

**Comment by GamerNoTitle** [comment]
> 500 服务器发生了以下错误： Server is currently under high load, we are unable to finish your requests at this time. Please try again later. Traceback (most recent call last): File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1823, in full_dispatch_request rv = self.dispatch_request() File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1799, in dispatch_request return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args) File "/app/app.py", line 170, in market_handler return market(app, request, g.lang) File "/app/utils/Register.py", line 59, in market weapon_target = weapon(weapon_item['OfferID'], weapon_item["Cost"]["85ad13f7-3d1b-5128-9eb2-7cd8ee0b5741"], lang=str(lang)) File "/app/utils/Weapon.py", line 36, in **init** c.execute( sqlite3.OperationalError: database is locked
> 
> 你可以尝试【刷新网页】或者点击下方的“重置网站数据”按钮来解决这个问题。 如果你已经点击了下面的按钮，但仍然出现了这个问题，请尝试清除浏览器的cookie来重置会话 如果上面这两种方法你都已经尝试过了，那么请带着此错误信息联系开发者！

这个问题正在修 #158

**Comment by wiop93256** [comment]
请问RIOT的API更新进度怎么样了？

**Comment by GamerNoTitle** [comment]
> 请问RIOT的API更新进度怎么样了？

API基本没怎么变，主要是登陆方面现在验证码弹的很频繁

我正在考虑让使用Valora的用户手动过验证码，不然靠个人开发者在开源的情况下解决还是太难了

**Comment by GamerNoTitle** [comment]
> > 请问RIOT的API更新进度怎么样了？
> 
> API基本没怎么变，主要是登陆方面现在验证码弹的很频繁
> 
> 我正在考虑让使用Valora的用户手动过验证码，不然靠个人开发者在开源的情况下解决还是太难了

另外 我正在重新写登录用的轮子

**Comment by GamerNoTitle** [comment]
鉴于拳头在数日前更新了登录过程，加入了hcaptcha验证码，且hcaptcha的版本较高，后期可能会改为用Cookie登录（access token登录方法现在依然可用）
Riot Games has added hcaptcha on login process, and the hcaptcha version is higher than I excepted. So Valora will changed into cookie login in the later development. (Access Token login method is still avaliable)

**Comment by ConnorDoesDev** [comment]
little english guide on how to get your cookie, for the non-chinese users :)
# Acquiring your cookie
1. go [here](https://account.riotgames.com/) and login
2. open developer tools using ctrl + shift + i (or right click->inspect element)
3. click on network
4. with the devtools menu still open, go to https://auth.riotgames.com/ (do NOT open a new tab!! stay in the same tab you used to log into the first page)
5. lotta stuff should pop up, click on the row that says "auth.riotgames.com"
6. scroll down till you see "REQUEST Headers"
7. click on it and scroll till you see an entry named "Cookie:"
8. copy the entire entry value
# Troubleshooting
- check if you copied the correct entry and make sure you **ONLY copied the value**, not the Cookie: part
- make sure you copied the cookie that was in **Request Headers**, not Response Headers
